type Record {
    id: ID!
    unit: Unit
    value: String
    start: DateTime
    end: DateTime
    references: [ReferenceInterface]
    submitted: DateTime
}

type Dataset {
    id: ID!
    # concept is either a Factor or Variable in the ontology
    concept: OntologyEntryInterface
    records: [Record]
    contributors: [Person]
    references: [ReferenceInterface]
}

type SubmittedRecord {
    id: ID  # may be null if a new record, or provided if an update
    unitId: Int!
    value: String
    start: DateTime
    end: DateTime
    referenceIds: [Int]
}

type SubmittedData {
    conceptId: ID!
    records: [SubmittedRecord]
    contributors: [Person]
    references: [ReferenceInterface]
}

enum SubmissionStatus {
    PENDING
    PROCESSING
    COMPLETED
    FAILED
}

type ItemError {
    index: Int!
    error: String!
}

type DatasetSubmission {
    datasetId: ID
    data: SubmittedData
    status: SubmissionStatus
    errors: [String]
    itemErrors: [ItemError]
}

type DatasetSummary {
    id: ID!
    concept: OntologyEntryInterface,
    subjects: [Subject]
    locations: [Location]
    blocks: [Unit]
    unit_count: Int!
    record_count: Int!
    start: DateTime
    end: DateTime
}
