# Main Entity Types
type Program {
    id: ID!
    name: String!
    fullname: String
    description: String
    contacts: [Person]
    references: [ReferenceInterface]
    trials: [Trial]
}

type Trial {
    id: ID!
    name: String!
    fullname: String
    description: String
    start: DateTime
    end: DateTime
    contacts: [Person]
    references: [ReferenceInterface]
    studies: [Study]
}

type Study {
    id: ID!
    name: String!
    fullname: String
    description: String
    practices: String
    start: DateTime
    end: DateTime
    design: Design
    licence: LegalReference
    references: [ReferenceInterface]
}
