interface ReferenceInterface {
    id: ID!
    description: String
}

type LegalReference implements ReferenceInterface {
    id: ID!
    description: String

    text: String
}

type ExternalReference implements ReferenceInterface {
    id: ID!
    description: String

    url: String
    externalId: String
}

type FileReference implements ReferenceInterface {
    id: ID!
    description: String

    filename: String
    fileId: ID
    contentType: String
}

type ExternalDataReference implements ReferenceInterface {
    id: ID!
    description: String

    url: String
    externalId: String

    format: DataFormat
    schema: String
}

type DataFileReference implements ReferenceInterface {
    id: ID!
    description: String

    filename: String
    fileId: ID
    contentType: String

    format: DataFormat
    schema: String
}

type FileSubmission {
    referenceId: Int
    status: SubmissionStatus
    progress: Int
    errors: [String]
}

enum FileStatus {
    ARCHIVED
    RETRIEVING
    AVAILABLE
    FAILED
}

type FileRetrieval {
    startedAt: DateTime
    progress: Int
}

type FileDownloadState {
    status: FileStatus!
    progress: FileRetrieval
}

type FileDownload {
    expiresAt: DateTime!
    url: String!
}


union ReferenceUnion = LegalReference | ExternalReference | ExternalDataReference | DataFileReference | FileReference