input LayoutInput {
    """ Location ID from Region, provide this only for the root layout in an arrangement """
    locationId: ID
    """ Ontology LayoutType identifier """
    typeId: ID!
    """ Axis labels """
    axes: [String!]
    """ Optional name for the layout """
    name: String
    """ Optional parent layout to construct multiplexed layout arrangements"""
    parentId: ID
    """ When parent is supplied, position according to parent layout axes must be provided."""
    position: [String]
}

input LayoutUpdate {
    id: ID
    """ Location ID from Region, provide this only for the root layout in an arrangement """
    locationId: ID
    typeId: ID
    axes: [String!]
    name: String
    parentId: ID
    position: [String]
}

extend type Mutation {
    arrangementsCreateLayout(
        layout: LayoutInput!
        controlTeamId: ID!
        release:ReadRelease
    ): BooleanPayload!
    arrangementsUpdateLayout(
        layout: LayoutUpdate!
    ): BooleanPayload!
    arrangementsDeleteLayout(
        id: ID!
    ): BooleanPayload!
}