input PositionInput {
    """
    ID of Location in a Region
    """
    locationId: ID!
    """
    ID of Layout in and Arrangement
    """
    layoutId: ID
    """
    Coordinates should be a list of values corresponding to the stored layout axes.
    """
    coordinates: [String]
    start: DateTime
    end: DateTime
}

input UnitInput {
    """
    ID of Subject in the ontology
    """
    subjectId: ID!
    germplasmId: ID

    name: String
    description: String
    """
    IDs of parent Units, of which this unit forms a component
    """
    parentIds: [ID]
    """
    IDs of child Units, which represent a component of this unit.
    """
    childrenIds: [ID]
}

input UnitUpdate {
    unitId: ID!
    subjectId: ID
    germplasmId: ID
    name: String
    description: String
    parentIds: [ID!]
    childrenIds: [ID!]
}

extend type Mutation {
    blocksCreateUnit(unit: UnitInput!, position: PositionInput): BooleanPayload!
    blocksUpdateUnit(unit: UnitUpdate!): BooleanPayload!
    blocksDeleteUnit(unitId: ID!): BooleanPayload!
    blocksAddPosition(unitId: ID!, position: PositionInput!): BooleanPayload!
    blocksRemovePosition(unitId: ID!, position: PositionInput!): BooleanPayload!
}
