input RecordInput {
    unitId: ID!
    value: String
    start: DateTime
    end: DateTime
    referenceIds: [ID]
}

input RecordUpdate {
    id: ID!
    unitId: ID
    value: String
    start: DateTime
    end: DateTime
    referenceIds: [ID]
}

input DatasetInput {
    studyId: ID!
    """ concept is either a Factor or Variable in the ontology """
    conceptId: ID!
    records: [RecordInput!]!
    contributorIds: [ID!]
    referenceIds: [ID!]
}

input DatasetUpdate {
    """
    Optionally provide a list of records to update
    """
    id: ID!
    studyId: ID
    conceptId: ID
    records: [RecordUpdate!]!
    contributorIds: [ID!]
    referenceIds: [ID!]
}

extend type Mutation {
    """
    Submission Payloads include a key, the data is processed asynchronously
    Poll the datasetsSubmission using the returned submission ID for status reports.
    """
    datasetsCreate(
        dataset: DatasetInput!
        controlTeamId: ID!
        release:ReadRelease
    ): SubmissionIdPayload!
    datasetsUpdate(dataset: DatasetUpdate!): SubmissionIdPayload!
    datasetsAddRecords(id: ID!, records: [RecordInput!]): SubmissionIdPayload!
    """Delete records from a dataset"""
    datasetsRemoveRecords(id: ID!, recordIds: [ID!]!): BooleanPayload!
}
