enum Reproduction {
    CLONAL
    SEXUAL
    APOMIXIS
}

enum GermplasmSourceType {
    UNKNOWN
    SEED
    TISSUE
    MATERNAL
    PATERNAL
}

input GermplasmSourceRelationship {
    sourceId: ID!
    sourceType: GermplasmSourceType!
    description: String
}

input GermplasmSinkRelationship {
    sinkId: ID!
    sourceType: GermplasmSourceType!
    description: String
}

# Program Mutations
input GermplasmInput {
    name: String!
    description: String
    synonyms: [String!]

    """
    Place of origin, a reference to a Location stored in Regions
    """
    originId: ID
    """
    Time sourced from origin
    """
    time: DateTime
    """
    Reproduction of germplasm, summarises the genetic impacts/requirements for maintenance
    """
    reproduction: Reproduction
    """
    Control methods (referenced in the ontology) to provide further details about how this germplasm is maintained
    """
    controlMethodIds: [ID!]
    """Authors of this germplasm entry (A list of personId)"""
    authorIds: [ID!] = []
    """References for ths germplasm entry (A list of referenceId)"""
    referenceIds: [ID!] = []
    """Source relationships"""
    sources: [GermplasmSourceRelationship!]
    """Sink relationships"""
    sinks: [GermplasmSinkRelationship!]
}

input GermplasmUpdate {
    id: ID!
    name: String
    description: String
    synonyms: [String!]
    originId: ID
    time: DateTime
    reproduction: Reproduction
    controlMethodIds: [ID!]
    authorIds: [ID!] = []
    referenceIds: [ID!] = []
    sources: [GermplasmSourceRelationship!]
    sinks: [GermplasmSinkRelationship!]
}

extend type Mutation {
    germplasmCreateEntry(entry: GermplasmInput!): BooleanPayload
    germplasmUpdateEntry(entry: GermplasmUpdate!): BooleanPayload
    germplasmDeleteEntry(entryId: ID!): BooleanPayload
}