enum VersionChange {MAJOR, MINOR, PATCH}

input TermInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    """People that established this entry (Person ID)"""
    authorIds: [ID!]
    """References for additional details, (Reference ID) e.g. a link to another ontology."""
    referenceIds: [ID!]
    """
    To establish a hierarchy and relationships among terms.
    Parents or children may be defined for any entry.
    """
    parentIds: [ID!]
    childIds: [ID!]
    subjectIds: [ID!]
    scaleIds: [ID!]
    categoryIds: [ID!]
    observationMethodIds: [ID!]
    traitIds: [ID!]
    variableIds: [ID!]
    controlMethodIds: [ID!]
    conditionIds: [ID!]
    factorIds: [ID!]
    eventIds: [ID!]
    locationTypeIds: [ID!]
    layoutTypeIDs: [ID!]
    designIds: [ID!]
    roleIds: [ID!]
    titleIds: [ID!]
}

input SubjectInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
    traitIds: [ID!]
    conditionIds: [ID!]
}

input TraitInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
    subjectIds: [ID!]!
}

input ConditionInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
}

input ScaleInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
    scaleType: ScaleType!
    """
    When defining a scale using existing categories, their identifiers may be listed in their proposed rank order.
    """
    categoryIds: [ID!]
}

input CategoryInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
    """
    When creating a category for an ordinal scale, a rank should be provided.
    """
    rank: Int
}

input ObservationMethodInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
    observationType: ObservationMethodType!
}

input VariableInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    traitId: ID!
    observationMethodId: ID!
    scaleId: ID!
}

input ControlMethodInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    controlType: ControlMethodType!
}

input FactorInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    conditionId: ID!
    controlMethodId: ID!
    scaleId: ID!
}

input EventInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    variableIds: [ID!]
    factorIds: [ID!]
    termIds: [ID!]
}

input LocationTypeInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
}

input DesignInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
}

input LayoutTypeInput {
    name: String!
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
    axes: [AxisType!]!
}

input TermUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    subjectIds: [ID!]
    scaleIds: [ID!]
    categoryIds: [ID!]
    observationMethodIds: [ID!]
    traitIds: [ID!]
    variableIds: [ID!]
    controlMethodIds: [ID!]
    conditionIds: [ID!]
    factorIds: [ID!]
    eventIds: [ID!]
    locationTypeIds: [ID!]
    layoutTypeIDs: [ID!]
    designIds: [ID!]
    roleIds: [ID!]
    titleIds: [ID!]
}

input SubjectUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
}

input TraitUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    subjectIds: [ID!]
}

input ConditionUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    subjectIds: [ID!]
}

input ScaleUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    scaleType: ScaleType!
    categoryIds: [ID!]
}

input CategoryUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    rank: Int
}

input ObservationMethodUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    observationType: ObservationMethodType!
}

input VariableUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    traitId: ID
    observationMethodId: ID
    scaleId: ID
}

input ControlMethodUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    controlType: ControlMethodType
}

input FactorUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    conditionId: ID
    controlMethodId: ID
    scaleId: ID
}

input EventUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]

    variableIds: [ID!]
    factorIds: [ID!]
    termIds: [ID!]
}

input LocationTypeUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
}

input DesignUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]
}

input LayoutTypeUpdate {
    id: ID!
    name: String
    description: String
    abbreviation: String
    synonyms: [String!]
    authorIds: [ID!]
    referenceIds: [ID!]
    parentIds: [ID!]
    childIds: [ID!]
    termIds: [ID!]

    axes: [AxisType!]
}

extend type Mutation {
    ontologyCreateTerm(term: TermInput!): BooleanPayload!
    ontologyCreateSubject(subject: SubjectInput!): BooleanPayload!
    ontologyCreateTrait(trait: TraitInput!): BooleanPayload!
    ontologyCreateCondition(condition: ConditionInput!): BooleanPayload!
    ontologyCreateScale(scale: ScaleInput!): BooleanPayload!
    ontologyCreateCategory(category: CategoryInput!): BooleanPayload!
    ontologyCreateObservationMethod(observationMethod: ObservationMethodInput!): BooleanPayload!
    ontologyCreateVariable(variable: VariableInput!): BooleanPayload!
    ontologyCreateControlMethod(controlMethod: ControlMethodInput!): BooleanPayload!
    ontologyCreateFactor(factor: FactorInput!): BooleanPayload!
    ontologyCreateEvent(event: EventInput!): BooleanPayload!
    ontologyCreateLocationType(locationType: LocationTypeInput!): BooleanPayload!
    ontologyCreateDesign(design: DesignInput!): BooleanPayload!
    ontologyCreateLayoutType(layoutType: LayoutTypeInput!): BooleanPayload!
    
    ontologyUpdateTerm(term: TermUpdate!): BooleanPayload!
    ontologyUpdateSubject(subject: SubjectUpdate!): BooleanPayload!
    ontologyUpdateTrait(trait: TraitUpdate!): BooleanPayload!
    ontologyUpdateCondition(condition: ConditionUpdate!): BooleanPayload!
    ontologyUpdateScale(scale: ScaleUpdate!): BooleanPayload!
    ontologyUpdateCategory(category: CategoryUpdate!): BooleanPayload!
    ontologyUpdateObservationMethod(observationMethod: ObservationMethodUpdate!): BooleanPayload!
    ontologyUpdateVariable(variable: VariableUpdate!): BooleanPayload!
    ontologyUpdateControlMethod(controlMethod: ControlMethodUpdate!): BooleanPayload!
    ontologyUpdateFactor(factor: FactorUpdate!): BooleanPayload!
    ontologyUpdateEvent(event: EventUpdate!): BooleanPayload!
    ontologyUpdateLocationType(locationType: LocationTypeUpdate!): BooleanPayload!
    ontologyUpdateDesign(design: DesignUpdate!): BooleanPayload!
    ontologyUpdateLayoutType(layoutType: LayoutTypeUpdate!): BooleanPayload!
    
    ontologyActivateEntries(entryIds: [ID!]!): BooleanPayload!
    ontologyDeprecateEntries(entryIds: [ID!]!): BooleanPayload!
    ontologyRemoveEntries(entryIds: [ID!]!): BooleanPayload!
    ontologyActivateRelationships(relationshipIds: [ID!]!): BooleanPayload!
    ontologyDeprecateRelationships(relationshipIds: [ID!]!): BooleanPayload!
    ontologyRemoveRelationships(relationshipIds: [ID!]!): BooleanPayload!
    ontologyCommitVersion(
        versionChange: VersionChange!,
        comment: String,
        licenceId: ID,
        copyrightId: ID
    ): BooleanPayload!
}