input TeamInput {
    """ Required name for the team """
    name: String!
    """ Optional full name for the team """
    fullname: String
    """ Optional parent team to extend an organisation"""
    parentId: ID
}

input TeamUpdate {
    id: ID!
    name: String
    fullname: String
}

extend type Mutation {
    organisationsCreateTeam(
        team: TeamInput!
    ): BooleanPayload!
    organisationsDeleteTeam(
        id: ID!
    ): BooleanPayload!
    organisationsUpdateTeam(
        team: TeamUpdate!
    ): BooleanPayload!
}