# Program Mutations
input ProgramInput {
    name: String!
    fullname: String
    description: String
    contactIds: [ID!] = []
    referenceIds: [ID!] = []
}

input ProgramUpdate {
    id: ID!
    name: String
    fullname: String
    description: String
    contactIds: [ID!]
    referenceIds: [ID!]
}

# Trial Mutations
input TrialInput {
    programId: ID!
    name: String!
    fullname: String
    description: String
    start: DateTime
    end: DateTime
    contactIds: [ID!] = []
    referenceIds: [ID!] = []
}

input TrialUpdate {
    id: ID!
    name: String
    fullname: String
    description: String
    start: DateTime
    end: DateTime
    contactIds: [ID!]
    referenceIds: [ID!]
}

# Study Mutations
input StudyInput {
    trialId: ID!
    name: String!
    fullname: String
    description: String
    practices: String
    start: DateTime
    end: DateTime
    datasetIds: [ID!] = []
    designId: ID
    licenceId: ID
    referenceIds: [ID!] = []
}

input StudyUpdate {
    id: ID!
    name: String
    fullname: String
    description: String
    practices: String
    start: DateTime
    end: DateTime
    datasetIds: [ID!]
    designId: ID
    licenceId: ID
    referenceIds: [ID!]
}

enum GroupingScope {
    STUDY_WIDE
    DATASET_SCOPED
}

input DatasetScopeInput {
    datasetIds: [ID!]!
}

input GroupingInput {
    studyId: ID!
    typeId: ID!
    name: String!
    scope: GroupingScope!
    dataset_scopes: [DatasetScopeInput!]
}

input GroupingUpdate {
    typeId: ID!
    name: String!
    dataset_scopes: [DatasetScopeInput!]
}

# Mutation type extensions for programs
extend type Mutation {
    # Program mutations
    programsCreateProgram(
        program: ProgramInput!
        controlTeamId: ID!
        release: ReadRelease
    ): BooleanPayload!
    programsUpdateProgram(program: ProgramUpdate!): BooleanPayload!
    programsDeleteProgram(id: ID!): BooleanPayload!

    # Trial mutations
    programsCreateTrial(
        trial: TrialInput!
        controlTeamId: ID!
        release: ReadRelease
    ): BooleanPayload!
    programsUpdateTrial(trial: TrialUpdate!): BooleanPayload!
    programsDeleteTrial(id: ID!): BooleanPayload!

    # Study mutations
    programsCreateStudy(
        study: StudyInput!
        controlTeamId: ID!
        release: ReadRelease
    ): BooleanPayload!
    programsUpdateStudy(study: StudyUpdate!): BooleanPayload!
    programsDeleteStudy(id: ID!): BooleanPayload!

    # Grouping mutations
    programsCreateGrouping(grouping: GroupingInput): BooleanPayload!
    programsUpdateGrouping(grouping: GroupingInput): BooleanPayload!
    programsDeleteGrouping(id: ID!): BooleanPayload!
    """Merging scopes
    If any of the datasetIds provided are in an existing scope,
    all datasetIds will be added to that scope.
    Otherwise, a new scope will be created.
    """
    programsMergeScope(groupingId: ID!, datasetIds:[ID!]): BooleanPayload!
}