# Program Mutations
input CreateProgramInput {
    name: String!
    fullname: String
    description: String
    contactIds: [ID!] = []
    referenceIds: [ID!] = []
}

input UpdateProgramInput {
    programId: ID!
    name: String
    fullname: String
    description: String
    contactIds: [ID!]
    referenceIds: [ID!]
}

# Trial Mutations
input CreateTrialInput {
    programId: ID!
    name: String!
    fullname: String
    description: String
    start: DateTime
    end: DateTime
    contactIds: [ID!] = []
    referenceIds: [ID!] = []
}

input UpdateTrialInput {
    trialId: ID!
    name: String
    fullname: String
    description: String
    start: DateTime
    end: DateTime
    contactIds: [ID!]
    referenceIds: [ID!]
}

# Study Mutations
input CreateStudyInput {
    trialId: ID!
    name: String!
    fullname: String
    description: String
    practices: String
    start: DateTime
    end: DateTime
    datasetIds: [ID!] = []
    designId: ID
    licenceId: ID
    referenceIds: [ID!] = []
}

input UpdateStudyInput {
    studyId: ID!
    name: String
    fullname: String
    description: String
    practices: String
    start: DateTime
    end: DateTime
    datasetIds: [ID!]
    designId: ID
    licenceId: ID
    referenceIds: [ID!]
}

# Mutation type extensions for programs
extend type Mutation {
    # Program mutations
    programsCreateProgram(program: CreateProgramInput!): BooleanPayload
    programsUpdateProgram(program: UpdateProgramInput!): BooleanPayload
    programsDeleteProgram(programId: ID!): BooleanPayload

    # Trial mutations
    programsCreateTrial(trial: CreateTrialInput!): BooleanPayload
    programsUpdateTrial(trial: UpdateTrialInput!): BooleanPayload
    programsDeleteTrial(trialId: ID!): BooleanPayload

    # Study mutations
    programsCreateStudy(study: CreateStudyInput!): BooleanPayload
    programsUpdateStudy(study: UpdateStudyInput!): BooleanPayload
    programsDeleteStudy(studyId: ID!): BooleanPayload
}