enum DataFormat {
    FASTA
    FASTQ
    ODGI
    HDF5
    CSV
    TSV
}

input LegalReferenceInput {
    description: String
    text: String!
}

input ExternalReferenceInput {
    description: String
    url: String!
    externalId: String
}

input ExternalDataReferenceInput {
    description: String
    url: String!
    externalId: String

    format: DataFormat!
    schema: String
}

input FileReferenceInput {
    description: String
    file: Upload!
}

input DataFileReferenceInput {
    description: String
    file: Upload!

    format: DataFormat!
    schema: String
}



input LegalReferenceUpdate {
    id: ID!
    description: String
    text: String!
}

input ExternalReferenceUpdate {
    id: ID!
    description: String
    url: String!
    externalId: String
}

input ExternalDataReferenceUpdate {
    id: ID!
    description: String
    url: String!
    externalId: String

    format: DataFormat!
    schema: String
}

input FileReferenceUpdate {
    id: ID!
    description: String
    file: Upload
}

input DataFileReferenceUpdate {
    id: ID!
    description: String
    file: Upload

    format: DataFormat!
    schema: String
}

extend type Mutation {
    referencesCreateLegal(
        reference: LegalReferenceInput!
        controlTeamId: ID!
        release: ReadRelease
    ): CreatedIdPayload!
    referencesCreateExternal(
        reference: ExternalReferenceInput!
        controlTeamId: ID!
        release: ReadRelease
    ): CreatedIdPayload!
    referencesCreateExternalData(
        reference: ExternalDataReferenceInput!
        controlTeamId: ID!
        release: ReadRelease
    ): CreatedIdPayload!

    """As for dataset submissions, creating a file is asynchronous and we are returned a key """
    referencesCreateFile(
        reference: FileReferenceInput
        controlTeamId: ID!
        release: ReadRelease
    ): FileIdPayload!
    referencesCreateDataFile(
        reference: DataFileReferenceInput
        controlTeamId: ID!
        release: ReadRelease
    ): FileIdPayload!
    
    referencesUpdateLegal(reference: LegalReferenceUpdate!): BooleanPayload!
    referencesUpdateExternal(reference: ExternalReferenceUpdate!): BooleanPayload!
    referencesUpdateExternalData(reference: ExternalDataReferenceUpdate!): BooleanPayload!

    referencesUpdateFile(reference: FileReferenceUpdate): FileIdPayload!
    referencesUpdateDataFile(reference: DataFileReferenceUpdate): FileIdPayload!
    
    referencesDelete(ids: [ID!]!): BooleanPayload!
    """ Request to make an archived file available for download """
    referencesRequestFileRetrieval(fileId: ID!): BooleanPayload!
}