enum DataFormat {
    FASTA
    FASTQ
    ODGI
    HDF5
    CSV
    TSV
}

input CreateLegalReferenceInput {
    description: String
    text: String!
}

input CreateExternalReferenceInput {
    description: String
    url: String!
    externalId: String
}

input CreateExternalDataReferenceInput {
    description: String
    url: String!
    externalId: String

    format: DataFormat!
    schema: String
}

input CreateFileReferenceInput {
    description: String
    file: Upload!
}

input CreateDataFileReferenceInput {
    description: String
    file: Upload!

    format: DataFormat!
    schema: String
}



input UpdateLegalReferenceInput {
    referenceId: ID!
    description: String
    text: String!
}

input UpdateExternalReferenceInput {
    referenceId: ID!
    description: String
    url: String!
    externalId: String
}

input UpdateExternalDataReferenceInput {
    referenceId: ID!
    description: String
    url: String!
    externalId: String

    format: DataFormat!
    schema: String
}

input UpdateFileReferenceInput {
    referenceId: ID!
    description: String
    file: Upload
}

input UpdateDataFileReferenceInput {
    referenceId: ID!
    description: String
    file: Upload

    format: DataFormat!
    schema: String
}

extend type Mutation {
    referencesCreateLegal(
        reference: CreateLegalReferenceInput!
        controlTeamId: ID!
    ): CreatedIdPayload!
    referencesCreateExternal(
        reference: CreateExternalReferenceInput!
        controlTeamId: ID!
    ): CreatedIdPayload!
    referencesCreateExternalData(
        reference: CreateExternalDataReferenceInput!
        controlTeamId: ID!
    ): CreatedIdPayload!

    """As for dataset submissions, creating a file is asynchronous and we are returned a key """
    referencesCreateFile(
        reference: CreateFileReferenceInput
        controlTeamId: ID!
    ): FileIdPayload!
    referencesCreateDataFile(
        reference: CreateDataFileReferenceInput
        controlTeamId: ID!
    ): FileIdPayload!
    
    referencesUpdateLegal(reference: UpdateLegalReferenceInput!): BooleanPayload!
    referencesUpdateExternal(reference: UpdateExternalReferenceInput!): BooleanPayload!
    referencesUpdateExternalData(reference: UpdateExternalDataReferenceInput!): BooleanPayload!

    referencesUpdateFile(reference: UpdateFileReferenceInput): FileIdPayload!
    referencesUpdateDataFile(reference: UpdateDataFileReferenceInput): FileIdPayload!
    
    referencesDelete(referenceIds: [ID!]!): BooleanPayload!
    """ Request to make an archived file available for download """
    referencesRequestFileRetrieval(fileId: ID!): BooleanPayload!
}