input GeoCoordinateInput {
    """Latitude in degrees according to ISO 6709"""
    latitude: Float!
    """Longitude in degrees according to ISO 6709"""
    longitude: Float!
    """Meters above WGS84 reference ellipsoid"""
    altitude: Float
    """UncertaIDy in meters associated with these coordinates"""
    uncertainty: Float
    """Additional coordinate description"""
    description: String
}

input LocationInput {
    name: String!
    """ Optional code for location, e.g. zip-code """
    code: String
    description: String
    address: String
    coordinates: [GeoCoordinateInput]
    """ Ontology LocationType identifier """
    typeId: ID!
    """ A parent location, required unless a country (see countries) """
    parentId: ID
}

input LocationUpdate {
    id: ID!
    name: String
    """ Optional code for location, e.g. zip-code """
    code: String
    description: String
    address: String
    coordinates: [GeoCoordinateInput]
    """ Ontology LocationType identifier """
    typeId: ID
    """ A parent location, required unless a country (see countries) """
    parentId: ID
}

extend type Mutation {
    regionsCreateLocation(
        location: LocationInput!
        controlTeamId: ID!
        release: ReadRelease
    ): BooleanPayload!,
    regionsUpdateLocation(
        location: LocationUpdate!
    ): BooleanPayload!,
    regionsDeleteLocation(
        id: ID!
    ): BooleanPayload!
}