import os

BREEDCAFS_NEO4J_PASSWORD = os.getenv('BREEDCAFS_NEO4J_PASSWORD')
BREEDCAFS_NEO4J_USERNAME = os.getenv('BREEDCAFS_NEO4J_USERNAME', 'neo4j')
BREEDCAFS_DB_NAME = os.getenv('BREEDCAFS_DB_NAME', 'graph.db')
BREEDCAFS_DB_HOST = os.getenv('BREEDCAFS_DB_HOST', 'localhost')
BREEDCAFS_DB_PORT = os.getenv('BREEDCAFS_DB_PORT', '7689')

BREEDCAFS_USER_NAME = os.getenv('BREEDCAFS_USER_NAME', 'BreedCAFS Migration')
